apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zanglab-bartweb-files-nfs-pvc
  namespace: zanglab
spec:
  storageClassName: zanglab-bartweb-files-sc
  accessModes:
    - ReadOnlyMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
