# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: bartweb-ceph-pvc
#   namespace: zanglab
# spec:
#   storageClassName: bartweb-ceph-sc
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bartweb-ceph-pvc
  namespace: zanglab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: bartweb-ceph-pv
  storageClassName: csi-cephfs-sc


#PVC not needed here,, the PV creates it. 
